#ifndef ADDRESSES_H
#define ADDRESSES_H

namespace Addresses{

	const DWORD INCOMING_DATA_STREAM = 0xA3BC20;
	const DWORD NEXT_INCOMING_DATA = 0x531C60;
	const DWORD GET_NEXT_INCOMING_CALL = 0x479802;

	const DWORD OUTGOING_DATA_STREAM = 0x812BF0;
	const DWORD OUTGOING_PACKET_CALL = 0x5312A0;
	const DWORD OUTGOING_LEN = 0xA3BC34;

	const DWORD OUTGOING_HOOK_ADDRESS = OUTGOING_PACKET_CALL + 0xA;

};

#endif